#!/usr/bin/env bash
# print best school for as long as x is not equal 4 or 8
x=1
while [[ x -le 10 ]]
do 
if (( x == 4 ))
then 
echo "bad luck"
elif (( x == 8 ))
then 
echo "good luck"
else
echo "Best School"
fi
(( x ++ ))
done
